### PR TITLE
Feat/o auth button styling

### PR DESCRIPTION
**Pull request by StephenTanksley**
# Description

This PR styles the re-usable wrapper component for the OAuth buttons. Provides custom CSS which will adapt buttons to look for images based on the provider prop declared at the instantiation of the component. Each new provider can be called by using the OAuth Button component and passing that prop.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [x] Test B - Manual testing in browser

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

### CODE REVIEW

**Review by nottolivc — COMMENTED** [review]
Are all of the background images for the buttons set to linkedin-default?

**Comment by StephenTanksley** [comment]
> Are all of the background images for the buttons set to linkedin-default?

Shouldn't be. 

Screen Shot 2020-05-12 at 9 46 41 AM

This code will pull the correct image based on the value passed to the Provider prop. Is it displaying only as LinkedIn?

**Comment by StephenTanksley** [comment]
> > Are all of the background images for the buttons set to linkedin-default?
> 
> Shouldn't be.
> 
> Screen Shot 2020-05-12 at 9 46 41 AM
> 
> This code will pull the correct image based on the value passed to the Provider prop. Is it displaying only as LinkedIn?

This is the observed behavior on my branch.

Screen Shot 2020-05-12 at 9 49 39 AM

**Comment by raythurman2386** [comment]
That's looking good man. That styled component is awesome

**Pull request merged**
