### PR TITLE
Feat/homepage prototype

### PR DESCRIPTION
**Pull request by nottolivc**
Description
Created a homepage dir with a marketing homepage prototype for feedback and review, added a React router with a private route component, and a basic dashboard component prototype that will be enhanced based on user type. Added/installed Apollo provider and CSS to Stephens register and login components for Material UI. Updated readme to reflect recent team decisions.
Fixes # (issue)
Trello steps for Frontend homepage, prototype, user login and register flow. REVIEW and ENHANCE.

Type of change
[ x ] New feature (non-breaking change which adds functionality)
Change Status
 Complete, tested, ready to review and merge
 Complete, but not tested (may need new tests)
[ x ] Incomplete/work-in-progress, PR is for discussion/feedback
How Has This Been Tested?
 Test A
 Test B
Checklist
[ x ] My code follows the style guidelines of this project
[ x ] I have performed a self-review of my own code
[ x ] My code has been reviewed by at least one peer
[ x ] I have commented my code, particularly in hard-to-understand areas
[ x ] I have made corresponding changes to the documentation
[ x ] My changes generate no new warnings
[ x ] I have added tests that prove my fix is effective or that my feature works
[ x ] New and existing unit tests pass locally with my changes
[ x ] There are no merge conflicts

### CODE REVIEW

**Comment by nottolivc** [comment]
Comments??

**Review by BPitts8019 — CHANGES_REQUESTED** [review]
I like most of what I see so far. However, I do have a few thoughts. `index.html` has some old references to files that no longer exist in the project: `logo192.png` and `manifest.json`. Please remove the lines that reference those files. The `theme-color` and `description` meta tags are unnecessary. At the very least, the description should be modified to reflect the purpose of the app.

Our components should avoid the `any` type as much as possible (implicit and explicit). The props for PrivateRoute have a defined type; something like `{component: Component, isAuthenticated: boolean, ...rest: any[]}`. Since we don't know what the `rest` array may contain, the use of `any` type seems appropriate for that case.

**Comment by Vyraal1** [comment]
[FE Styling (Login, Registration,Dashboard)](https://trello.com/c/M3LnT2dz/55-fe-styling-login-registrationdashboard)

**Comment by nottolivc** [comment]
merging after UX team meeting... implemented serval changes based on comments and review to give the project a working base of components. Material UI Textfields still needed in forms, authentication helper functions implemented, also basic apollo client has been added, query structure needed and mutations for dashboard, working prototype error free for now, testing needed.

**Pull request merged**
